SELECT E3.ID
FROM ECOLI_DATA E3
JOIN ECOLI_DATA E2 ON E2.ID = E3.PARENT_ID
JOIN ECOLI_DATA E1 ON E1.ID = E2.PARENT_ID AND ISNULL(E1.PARENT_ID)=TRUE
ORDER BY E3.ID

## 서브쿼리
# SELECT ED3.ID
# FROM ECOLI_DATA AS ED3
# WHERE ED3.PARENT_ID IN (
#     SELECT ED2.ID
#     FROM ECOLI_DATA AS ED2
#     WHERE ED2.PARENT_ID IN (
#         SELECT ED.ID
#         FROM ECOLI_DATA AS ED
#         WHERE ED.PARENT_ID IS NULL
#     )
# )
# ORDER BY ED3.ID ASC