# 1
SELECT R.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS SCORE
FROM REST_REVIEW AS R
JOIN REST_INFO AS I ON I.REST_ID = R.REST_ID
GROUP BY R.REST_ID
HAVING I.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, I.FAVORITES DESC

# # 2 서브쿼리
# SELECT S.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, S.SCORE
# FROM (
#     SELECT R.REST_ID, ROUND(AVG(R.REVIEW_SCORE)) AS SCORE
#     FROM REST_REVIEW AS R
#     GROUP BY R.REST_ID
# ) S
# JOIN REST_INFO AS I ON I.REST_ID = S.REST_ID
# WHERE I.ADDRESS LIKE '서울%'
# ORDER BY S.SCORE DESC, I.FAVORITES DESC