SELECT MONTH(START_DATE) MONTH, CAR_ID, COUNT(*) RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE 08<=MONTH(START_DATE) AND MONTH(START_DATE)<=10
    AND CAR_ID IN (SELECT CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                  WHERE 08<=MONTH(START_DATE) AND MONTH(START_DATE)<=10
                  GROUP BY CAR_ID
                  HAVING COUNT(*)>=5)
GROUP BY MONTH(START_DATE), CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC