# # 1
# SELECT DISTINCT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
# FROM SKILLCODES S, DEVELOPERS D
# WHERE (S.CODE & D.SKILL_CODE) > 0
#     AND S.NAME IN ('Python','C#')
# ORDER BY D.ID ASC;

# 2
SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS
WHERE SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')
    OR SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')
ORDER BY ID ASC;